#!/bin/bash

# Counts the number of pages in the given Xournal documents.

# License (BSD-3-clause)
# ======================
#
# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# - Neither the name of the Martin Ueding nor the names of his contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -u

# Cost of one sheet of paper, measured in €. This assumes that a box with 2500
# sheets costs 19.95€.
cost_per_page=0.00798

# Height per page, measured in meters.
height_per_page=0.0001

# Mass per page, measured in kilograms.
mass_per_page=0.005

sum=0

for file in "$@"
do
	case "$file" in
		*.xoj)
			pages="$(zgrep -Ec '<page' "$file")"
			;;
		*.pdf)
			pages="$(grep -Ec '/Page$' "$file")"
			;;
	esac
	sum=$((sum + pages))
	printf "%3d pages in %s\n" "$pages" "$file"
done

height=$(python -c "print $height_per_page * $sum")
cost=$(python -c "print $cost_per_page * $sum")
mass=$(python -c "print $mass_per_page * $sum")

echo

echo "Total:"
echo "    $sum pages."
echo "    $height meters in height."
echo "    $mass kilograms"
echo "    $cost €."
