#!/bin/bash
# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

# Counts the number of pages in the given Xournal documents.

set -e
set -u

sum=0

for file in "$@"
do
	pages="$(gunzip -c "$file" | grep '<page' | wc -l)"
	sum=$((sum + pages))
	echo "$file has $pages"
done
