#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

import argparse
import subprocess

__docformat__ = "restructuredtext en"

cost_per_page=0.00798
"""
Cost of one sheet of paper, measured in €. This assumes that a box with 2500
sheets costs 19.95€.
"""

height_per_page=0.0001
"Height per page, measured in meters."

mass_per_page=0.005
"Mass per page, measured in kilograms."

def main():
    options = _parse_args()

    total_pages = 0

    for filename in options.files:
        pages = 0

        if filename.endswith(".xoj.pdf"):
			# Ignore exported Xournal files. The original files will be counted
			# in the next case.
            continue
        elif filename.endswith(".xoj"):
            pages = get_xournal_pages(filename)
        elif filename.endswith(".pdf"):
            pages = get_pdf_pages(filename)
        elif filename.endswith(".jpg"):
            pages = 1

        total_pages += pages

        print "{pages:3d} {filename}".format(
            pages=pages,
            filename=filename,
        )

    print
    print "Total"
    print "    {total} pages".format(total=total_pages)
    print "    {height:.3f} meters in height".format(height=height_per_page*total_pages)
    print "    {mass:.3f} kilograms".format(mass=mass_per_page*total_pages)
    print "    {cost:.2f} €".format(cost=cost_per_page*total_pages)

def get_xournal_pages(filename):
    try:
        count = subprocess.check_output(["zgrep", "-Ec", "<page", filename])
    except subprocess.CalledProcessError:
        return 0
    else:
        return int(count)

def get_pdf_pages(filename):
    try:
        pdfinfo = subprocess.check_output(["pdfinfo", filename]).split("\n")
    except subprocess.CalledProcessError:
        return 0
    else:
        for line in pdfinfo:
            if line.startswith("Pages:"):
                parts = line.split()
                return int(parts[-1])

def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="", description="")
    parser.add_argument("files", metavar="files", type=str, nargs="+",
                   help="Filenames to process")

    return parser.parse_args()


if __name__ == "__main__":
    main()
